### ISSUE TITLE
Visiualization demo?

### ISSUE THREAD

**Issue by RuoyuChen10** [ntubiolin/xcos#9]
Thanks for your work, I think it's a great idea for explainable face verification, however, I found confuse about one:

That's in `visualize_xcos_one_example.ipynb`, an example for visiualization, after define the model, it seems that didn't set:

```python
model.eval()
```

And after I set `model.eval()`, the output is change.

Could you confirm this? Or something I may misunderstand for loading pretrained model?

Thx, looking forward to your rely!

**Comment by ntubiolin** [comment]
Thank you for pointing out the issue.
I think it's a bug. The model.eval() should be added to the jupyter notebook. I will push a patched version later.

**Comment by ntubiolin** [comment]
I have fix it in commit f85f0d4c9dd342536583c9a883b2217bcf6ad660. Thanks for reminding me!
